steps:   
  #Run Software Composition Analysis (SCA security scan) using Snyk
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN="c06e43d9-2933-4a18-aa47-e0205ea2f3df"
          export SNYK_TOKEN
          mvn snyk:test -fn
options:
  logging: CLOUD_LOGGING_ONLY