steps:   
  #Run Software Composition Analysis (SCA security scan) using Snyk
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=04383805-c688-4dae-bc2d-d3985c095581
          export SNYK_TOKEN
          mvn snyk:test -fn
options:
  logging: CLOUD_LOGGING_ONLY